#!/bin/bash
# SBATCH --time=0-00:05:00   ## days-hours:minutes:seconds
# SBATCH --mem 16000M         ## 16GB ram (hardware ratio is < 4GB/core)
# SBATCH --ntasks=1          ## Not strictly necessary because default is 1
# SBATCH --cpus-per-task=32   ## ask for 32 cpus (Use greater than 1 for parallelized jobs)
# SBATCH --output=--output=home/$USER/scratch/logs/job_%j.out

module load mamba
source activate lpdaac_vitals

echo 'HLS download starting.'

python ~/home/nrietz/TundraPreFire/code/data_download/HLS_preprocessing.py

echo 'finished'