#!/bin/bash
#SBATCH --time=0-00:05:00   ## days-hours:minutes:seconds
#SBATCH --cpus-per-task=32   ## ask for 32 cpus (Use greater than 1 for parallelized jobs)
#SBATCH --nodes=1
#SBATCH --output=/logs/job_%j.out
#SBATCH --mem-per-cpu=3850
#SBATCH --array=0-20

module load mamba
source activate lpdaac_vitals

echo 'HLS processing starting.'

cd ~/home/nrietz/TundraPreFire/

UTM_TILEID_FILE="code/data_processing/tile.txt"

# Get total number of lines
NUM_LINES=$(wc -l < "$UTM_TILEID_FILE")

# Set number of tasks
NUM_TASKS=20  # Should match the --array size

# Compute chunk size (ceiling division)
CHUNK_SIZE=$(( (NUM_LINES + NUM_TASKS - 1) / NUM_TASKS ))

# Compute start and end lines for this task
START=$(( SLURM_ARRAY_TASK_ID * CHUNK_SIZE + 1 ))
END=$(( START + CHUNK_SIZE - 1 ))

# Extract lines for this task
sed -n "${START},${END}p" "$UTM_TILEID_FILE" > task_${SLURM_ARRAY_TASK_ID}.txt

# Execute HLS preprocessing script with the split UTM tile id file
python code/data_processing/HLS_preprocessing.py task_${SLURM_ARRAY_TASK_ID}.txt

echo 'finished'