---
title: "Extracting data and analysis of dNBR"
output: html_notebook
---

Data pre-processing is handled in python. Sampling pixel values and data analysis in R.
```{r}
library(terra)
library(tidyterra)
library(rts)

library(gt)
library(tidyverse)
library(cowplot)
library(patchwork)
print(getwd())
```

## Loading and preparing data:
```{r}
dnbr <- rast("./data/raster/hls/dNBR/HLS.L30.T54WXE.2020254T020729.v2.0_dNBR_cropped.tif") * 1000

# Load features (fire perimeters and ROIs)
fire_perimeters_2020 <- vect("./data/feature_layers/fire_atlas/final_viirs2020.gpkg")
roi <- vect("./data/feature_layers/roi.geojson")

fire_within_roi <- terra::intersect(fire_perimeters_2020, roi)
plot(fire_within_roi,"duration")
```
## Dissolve fire perimeters that lie in the ROI to one
```{r}
fire_union_roi <- terra::aggregate(fire_within_roi) %>%
  project(crs(dnbr))

fire_perimeter_buffered <- buffer(fire_union_roi, 1200)

plot(fire_union_roi)
plot(fire_perimeter_buffered,add = TRUE)
```
```{r}
binwidth <- 20

dnbr_in_perimeter <- mask(dnbr, fire_perimeter_buffered, updatevalue = NA)

p1 <- ggplot() +
  geom_spatraster(data = dnbr_in_perimeter) +
  scale_fill_viridis_c(option = "inferno",
                       na.value = "white",
                       name = "dNBR") +
  theme_cowplot()

p2 <- ggplot(data = dnbr_in_perimeter, aes(x = NBR)) +
  geom_histogram(binwidth = binwidth, color = "black", fill = "indianred1") +
  xlim(c(-500,1000)) +
  labs(
      title = "Histogram of dNBR",
      x = "dNBR Values",
      y = "Frequency"
    ) +
  theme_cowplot()

p1 + p2

# ggsave2("figures/expl_dNBR_hist.png",bg = "white")
```

## Extract pixels within fire perimeter
```{r}
# Set dNBR bin size for sampling (dNBR * 1000)
binwidth <- 20

# get bins for the raster
bins <- seq(minmax(dnbr_in_perimeter)[1],minmax(dnbr_in_perimeter)[2],binwidth)

# Set proportion of sampled values per bin
nsample <- 1e4

# Create binned raster for sampling
rast_binned <- classify(dnbr_in_perimeter,
                        bins, 
                        include.lowest=TRUE,
                        brackets=TRUE)


# Sample n pixels and mask with burn perimeter
random_points <- spatSample(rast_binned, nsample, 
                            # method = "stratified",
                            method = "random",
                            values = FALSE,
                            as.points = TRUE) %>% 
  mask(fire_union_roi) 

# Export points as gpkg
writeVector(random_points, filename = "data/feature_layers/random_points.gpkg")

# Extract data at random points 
dnbr_sample <- terra::extract(dnbr, random_points,ID = FALSE, xy = TRUE) %>% 
  drop_na() 

p3 <- ggplot(data = dnbr_sample, aes(x = NBR)) +
  geom_histogram(binwidth = binwidth, color = "black", fill = "orange") +
  xlim(c(-500,1000)) +
  labs(
      title = "Histogram of dNBR (sampled)",
      x = "dNBR Values",
      y = "Frequency"
    ) +
  theme_cowplot()

p2 / p3 
ggsave2("figures/expl_dNBR_hist_vs_sampled.png",bg = "white")

# Export dataframe to csv
write.csv(dnbr_sample, file = "data/tables/dnbr_sample_test_roi.csv")
```

## Check spatial autocorrelation of Random points:
```{r}
library(spdep)

knn <- knn2nb(knearneigh(dnbr_sample[c("x","y")], k = 5))

# Convert neighbors to weights
weights <- nb2listw(knn, style = "W")

# Compute Moran's I
moran_i <- moran.test(dnbr_sample$NBR, listw = weights)

ggplot() +
  geom_spatraster(data = dnbr_in_perimeter) +
  scale_fill_viridis_c(option = "inferno",
                       na.value = "white",
                       name = "dNBR") +
  geom_spatvector(data = random_points) +
  labs(title = sprintf("Randomly samlped points\nMoran's I: %.2f(p-value: %.4f)", 
       moran_i$estimate[1],moran_i$p.value)) +                   
  theme_cowplot()

ggsave2("figures/stratified_random_points_moranI.png",bg = "white")

```

## Stack NDMI rasters
```{r}
HLS_DIR <- "data/raster/hls/"

assign_rast_time <- function(lyr) {
  # Extract the layer's timestamp
  timestamp <- sub(
    ".*\\.(\\d{7}T\\d{6}).*\\.tif$", "\\1",
    basename(sources(lyr))
  )

  # Convert string to datetime
  datetime <- as.POSIXct(timestamp, format = "%Y%jT%H%M%S", tz = "UTC")

  # Assign time to raster layer
  terra::time(lyr, "seconds") <- datetime
  # names(lyr) <- datetime

  return(lyr)
}

# List NDMI COGs
ndmi_files_s30 <- list.files(HLS_DIR,
  pattern = "S30.T54WXE.*NDMI_cropped\\.tif$"
)
ndmi_files_l30 <- list.files(HLS_DIR,
  pattern = "L30.T54WXE.*NDMI_cropped\\.tif$"
)

ndmi_s30 <- rast(paste0(HLS_DIR, ndmi_files_s30))
ndmi_s30 <- sapp(ndmi_s30, assign_rast_time)

ndmi_l30 <- rast(paste0(HLS_DIR, ndmi_files_l30))
ndmi_l30 <- sapp(ndmi_l30, assign_rast_time)
ndmi_l30 <- project(ndmi_l30, crs(ndmi_s30))

ndmi <- c(ndmi_s30, ndmi_l30)
ndmi
```

Extract NDMI values at random points
```{r}
# create raster time series object
rt <- rts(ndmi, time(ndmi))

df_ndmi <- terra::extract(rt, random_points) %>%
  t() %>%
  as.tibble()

summary(df_ndmi)

# Reshape from wide to long format
count_df <- df_ndmi %>%
  summarise(across(everything(), ~ sum(!is.na(.)))) %>% # Count non-NA values
  pivot_longer(
    cols = everything(),
    names_to = "datetime",
    values_to = "count"
  ) %>%
  mutate(
    datetime = ymd_hms(datetime),
    scene_nr = 1:nrow(.)
  ) 


count_df %>%
  select(-scene_nr) %>%
  gt() %>%
  gtsave("data/tables/Nsamples_NDMI.html")

# Plot the number of non-NA observations over time
ggplot(count_df, aes(x = scene_nr, y = count)) +
  geom_bar(stat = "identity", width = 0.8) +
  labs(
    x = "",
    y = "Number of Non-NA Observations"
  ) +
  scale_x_discrete(labels = format(count_df$datetime, "%d %b")) +
  theme_cowplot()
ggsave2("figures/Nsamples_NDMI.png",bg = "white")

```